services:
  postgres:
    image: postgres:16
    container_name: jobboard-postgres
    restart: always
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ff_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobboard"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobboard-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules # Защищает модули контейнера
      - /app/dist         # КРИТИЧНО: Защищает папку билда от удаления хостом
      - ./uploads:/app/uploads
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/jobboard
      JWT_SECRET: secret
      PORT: 5000
      NODE_ENV: production
      UPLOAD_DIR: /app/uploads
    # Мы убираем npx prisma migrate deploy из команды старта, чтобы она не мешала запуску, если база не готова
    command: >
      sh -lc "until nc -z postgres 5432; do echo 'Waiting for DB...'; sleep 1; done;
      node dist/index.js"

volumes:
  ff_postgres_data: